### ISSUE TITLE
got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by famiji** [bvalot/pyMLST#14]
Hi
I install this too by mamba
when i try to import database, i receive a sql error
```
wgmlst import Cp.db "Clostridium perfringens" --force
[INFO: 2023-03-02 11:51:43,558] One element found : Clostridium perfringens
[INFO: 2023-03-02 11:51:43,558] Downloading the core genome...
Traceback (most recent call last):
  File "/home/fmj/miniconda3/envs/pymlst/bin/wgmlst", line 10, in <module>
    sys.exit(wg())
             ^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/wg/commands/import.py", line 57, in cli
    with pymlst.open_wg(os.path.abspath(database)) as mlst:
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/wg/core.py", line 40, in open_wg
    mlst = WholeGenomeMLST(file, ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/wg/core.py", line 442, in __init__
    self.__database = DatabaseWG(file, ref)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/wg/core.py", line 63, in __init__    engine = utils.get_updated_engine(file, 'wg')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/common/utils.py", line 143, in get_updated_engine
    check_type(conn, module)
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/common/utils.py", line 113, in check_type
    set_type(conn, mlst_type)
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/common/utils.py", line 126, in set_type
    conn.execute(
TypeError: Connection.execute() got an unexpected keyword argument 'name'
```
Could you help me finding the mistake i do?

cheers.

**Comment by bvalot** [comment]
Hi,

I have no problem with your command on my installation.
Do you have internet in this computer? Because the command download the database from cgsmlt.org.
Or do you have permission on the folder you want to create the database?

```
wgmlst import Cp.db "Clostridium perfringens" --force
[INFO: 2023-03-02 08:56:08,657] One element found : Clostridium perfringens
[INFO: 2023-03-02 08:56:08,657] Downloading the core genome...
[INFO: 2023-03-02 08:56:11,085] Reverse-complemented genes: 926
[INFO: 2023-03-02 08:56:11,085] Database initialized
```
Benoit

**Comment by famiji** [comment]
I'm sure I have no problems connecting to the network and creating files

**Comment by bvalot** [comment]
No idea.

Download this file:
`wget https://raw.githubusercontent.com/bvalot/pyMLST/master/tests/data/wg/cgmlst_schema.fasta`

and try this command:
`wgMLST create E.coli.db cgmlst_schema.fasta`

**Comment by famiji** [comment]
I try it, this is the result.
```
(pymlst) fmj@qood:~$ wget https://raw.githubusercontent.com/bvalot/pyMLST/master/tests/data/wg/cgmlst_schema.fasta
--2023-03-02 16:27:26--  https://raw.githubusercontent.com/bvalot/pyMLST/master/tests/data/wg/cgmlst_schema.fasta
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2367809 (2.3M) [text/plain]
Saving to: ‘cgmlst_schema.fasta’

cgmlst_schema.fasta                 100%[===================================================================>]   2.26M  62.3KB/s    in 62s

2023-03-02 16:33:17 (37.3 KB/s) - ‘cgmlst_schema.fasta’ saved [2367809/2367809]

(pymlst) fmj@qood:~$ wgMLST create E.coli.db cgmlst_schema.fasta
Traceback (most recent call last):
  File "/home/fmj/miniconda3/envs/pymlst/bin/wgMLST", line 10, in <module>
    sys.exit(wg())
             ^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/wg/commands/create.py", line 33, in cli
    with pymlst.open_wg(os.path.abspath(database)) as mlst:
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/wg/core.py", line 40, in open_wg
    mlst = WholeGenomeMLST(file, ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/wg/core.py", line 442, in __init__
    self.__database = DatabaseWG(file, ref)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/wg/core.py", line 63, in __init__
    engine = utils.get_updated_engine(file, 'wg')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/common/utils.py", line 143, in get_updated_engine
    check_type(conn, module)
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/common/utils.py", line 113, in check_type
    set_type(conn, mlst_type)
  File "/home/fmj/miniconda3/envs/pymlst/lib/python3.11/site-packages/pymlst/common/utils.py", line 126, in set_type
    conn.execute(
TypeError: Connection.execute() got an unexpected keyword argument 'name'
```

**Comment by bvalot** [comment]
ok, same problem.

Which python version do you use?

**Comment by famiji** [comment]
+ python                              3.11.0  h10a6764_1_cpython   conda-forge/linux-64     Cached

**Comment by bvalot** [comment]
Can you try to install pymlst on python 3.9 environnement?

**Comment by bvalot** [comment]
`conda create -n "pymlst3.9" python=3.9 pymlst`

**Comment by famiji** [comment]
I followed your advice, but failed again

**Comment by bvalot** [comment]
you need to activate the good environnement
`which wgMLST`
`conda activate pymlst3.9`

**Comment by famiji** [comment]
/home/fmj/miniconda3/envs/pymlst3.9/bin/wgMLST``

**Comment by bvalot** [comment]
Normally, it must work with this version of python.

Can you report this command result:
`python --version`

**Comment by bvalot** [comment]
And you have the same error with the import commad?

**Comment by famiji** [comment]
Yes,it still error.
Although we haven't found the problem yet, thank you for your patience and timely response.

**Comment by famiji** [comment]
a new error appear
```
[INFO: 2023-03-02 16:55:24,099] One element found : Clostridium perfringens
[INFO: 2023-03-02 16:55:24,099] Downloading the core genome...
Traceback (most recent call last):
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/pymlst/common/web.py", line 231, in get_cgmlst_file
    iterator = next(SeqIO.parse(os.path.join(fas_tmp, fasta), 'fasta'))
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/Bio/SeqIO/__init__.py", line 605, in parse
    return iterator_generator(handle)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/Bio/SeqIO/FastaIO.py", line 223, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/Bio/SeqIO/Interfaces.py", line 45, in __init__
    self.stream = open(source, "r" + mode)
OSError: [Errno 24] Too many open files: '/tmp/tmp81po3jrs/fas/CPF_RS01715.fasta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fmj/miniconda3/envs/pymlst3.92/bin/wgmlst", line 10, in <module>
    sys.exit(wg())
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/pymlst/wg/commands/import.py", line 52, in cli
    skipped = web.get_cgmlst_file(url, tmp)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/pymlst/common/web.py", line 237, in get_cgmlst_file
    return skipped
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/tempfile.py", line 830, in __exit__
    self.cleanup()
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/tempfile.py", line 834, in cleanup
    self._rmtree(self.name)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/tempfile.py", line 816, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/shutil.py", line 730, in rmtree
    onerror(os.open, path, sys.exc_info())
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/shutil.py", line 727, in rmtree
    fd = os.open(path, os.O_RDONLY)
OSError: [Errno 24] Too many open files: '/tmp/tmp81po3jrs'
```

**Comment by bvalot** [comment]
The first problem is link to the change of SQLachemy library from 1.4 to 2.0 version.

Try the command :
`wgMLST create E.coli.db cgmlst_schema.fasta`

**Comment by famiji** [comment]
```
(pymlst3.92) fmj@qood:~$ wgMLST create E.coli.db cgmlst_schema.fasta
Usage: wgMLST create [OPTIONS] DATABASE COREGENE
Try 'wgMLST create -h' for help.

Error: Database alreadly exists, use --force to override it
(pymlst3.92) fmj@qood:~$ wgMLST create E.coli.db cgmlst_schema.fasta --force
Traceback (most recent call last):
  File "/home/fmj/miniconda3/envs/pymlst3.92/bin/wgMLST", line 10, in <module>
    sys.exit(wg())
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/pymlst/wg/commands/create.py", line 33, in cli
    with pymlst.open_wg(os.path.abspath(database)) as mlst:
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/pymlst/wg/core.py", line 40, in open_wg
    mlst = WholeGenomeMLST(file, ref)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/pymlst/wg/core.py", line 442, in __init__
    self.__database = DatabaseWG(file, ref)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/pymlst/wg/core.py", line 63, in __init__
    engine = utils.get_updated_engine(file, 'wg')
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/pymlst/common/utils.py", line 143, in get_updated_engine
    check_type(conn, module)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/pymlst/common/utils.py", line 113, in check_type
    set_type(conn, mlst_type)
  File "/home/fmj/miniconda3/envs/pymlst3.92/lib/pypy3.9/site-packages/pymlst/common/utils.py", line 126, in set_type
    conn.execute(
TypeError: execute() got an unexpected keyword argument 'name'
```

**Comment by famiji** [comment]
I executed the following command and the result was successful
```
 mamba install SQLAlchemy=1.4
 ulimit -n 2048
 wgmlst import Cp.db "Clostridium perfringens" --force
```

**Comment by bvalot** [comment]
good.

I can check to update to SQLAlchemy 2.0 with no pression.
